# requires curl and sqlite3 

CC=g++
CGLAGS=-c -Wall
SOURCES=main.cpp Greenhouse.cpp DataService.cpp
EXECUTABLE=greenhouse

all:
	g++ main.cpp Greenhouse.cpp DataService.cpp -o greenhouse -lcurl -lsqlite3 -Wall -g
