.TH "DataService" 3 "Tue Mar 12 2013" "Version 0.5" "Greenhouse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataService \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataService\fP ()"
.br
.ti -1c
.RI "void \fBrefreshDataService\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataService::DataService ()"
DataService\&.cpp 
.SH "Member Function Documentation"
.PP 
.SS "void DataService::refreshDataService ()"
Read the latest results from the DB and create the CSV file 

.SH "Author"
.PP 
Generated automatically by Doxygen for Greenhouse from the source code\&.
