.TH "Greenhouse" 3 "Tue Mar 12 2013" "Version 0.5" "Greenhouse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Greenhouse \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGreenhouse\fP (const char *ipAddress)"
.br
.ti -1c
.RI "float \fBgetTemp\fP ()"
.br
.ti -1c
.RI "float \fBgetHumidity\fP ()"
.br
.ti -1c
.RI "float \fBgetLumens\fP ()"
.br
.ti -1c
.RI "float \fBgetSoilMoisture\fP ()"
.br
.ti -1c
.RI "const char * \fBgetArduinoIP\fP ()"
.br
.ti -1c
.RI "time_t \fBgetTime\fP ()"
.br
.ti -1c
.RI "void \fBrefreshReadings\fP ()"
.br
.ti -1c
.RI "void \fBprintReadings\fP ()"
.br
.ti -1c
.RI "void \fBcreateCSV\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Greenhouse from the source code\&.
